services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ds_24_test
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    depends_on:
      - postgres
    environment:
      POSTGRES_URL: "postgresql://root:root@postgres:5432/ds_24_test"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["sh", "-c", "npx prisma migrate dev --name init && npm run start:dev"]

volumes:
  pgdata: